-- Create system_errors table
CREATE TABLE public.system_errors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    error_message text NOT NULL,
    error_stack text,
    error_type text NOT NULL, -- 'JAVASCRIPT', 'REACT_RENDER', 'HYDRATION', 'API_NET', 'API_SERVER', 'DATA_INTEGRITY', 'RESOURCE_LOAD', 'GOOGLE_MAPS', 'GEOLOCATION', 'ROUTING', 'STORAGE', 'NATIVE_APP', 'AUTH_SESSION', 'UNKNOWN'
    severity text DEFAULT 'error', -- 'error', 'critical', 'warning'
    url text, -- Current URL
    user_agent text, -- Browser/Device info
    user_id uuid REFERENCES auth.users(id), -- Nullable, connected to auth.users
    metadata jsonb, -- Flexible JSON for connection info, breadcrumbs, etc.
    resolved boolean DEFAULT false
);

-- Enable Row Level Security
ALTER TABLE public.system_errors ENABLE ROW LEVEL SECURITY;

-- Policy: Allow INSERT for everyone (anon and authenticated)
-- We need execution logs from users who might not be logged in or when auth fails.
CREATE POLICY "Enable insert for all users" 
ON public.system_errors 
FOR INSERT 
WITH CHECK (true);

-- Policy: Allow SELECT for service_role only (Admin/Dashboard usage)
-- Regular users should not see other people's error logs.
CREATE POLICY "Enable select for service_role only" 
ON public.system_errors 
FOR SELECT 
USING (auth.role() = 'service_role');

-- Optional: Index on error_type for faster filtering
CREATE INDEX idx_system_errors_type ON public.system_errors (error_type);
-- Optional: Index on created_at for time-range queries
CREATE INDEX idx_system_errors_created_at ON public.system_errors (created_at DESC);
